### ISSUE TITLE
test

### ISSUE THREAD

**Issue by KamilaLis** [pmatysiak/licz_wyrazy#1]
test

**Comment by pmatysiak** [comment]
Co z tym masłem?

**Comment by KamilaLis** [comment]
Za mało go!

________________________________
Od: pmatysiak <notifications@github.com>
Wysłane: środa, 24 lutego 2021 13:29
Do: pmatysiak/licz_wyrazy <licz_wyrazy@noreply.github.com>
DW: Kamila Lis <kamila.lis@outlook.com>; Author <author@noreply.github.com>
Temat: Re: [pmatysiak/licz_wyrazy] test (#1)


Co z tym masłem?

**Comment by pmatysiak** [comment]
Masełko zawsze w cenie :3

śr., 24 lut 2021 o 13:30 Kamila Lis <notifications@github.com> napisał(a):
